In [1]:
import numpy as np

In [2]:
a=np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [29]:
b=np.array([1,23,4,5,6,36,7,8,15,19,20,2,9,3,11,16,17,18])
b=b.reshape(6,3)

In [30]:
b

array([[ 1, 23,  4],
       [ 5,  6, 36],
       [ 7,  8, 15],
       [19, 20,  2],
       [ 9,  3, 11],
       [16, 17, 18]])

In [31]:
np.argsort(b, axis=0)

array([[0, 4, 3],
       [1, 1, 0],
       [2, 2, 4],
       [4, 5, 2],
       [5, 3, 5],
       [3, 0, 1]], dtype=int64)

In [24]:
np.argmin(b)

0

In [25]:
np.argmax(b)

5